/**
 * Training infrastructure for GRPO, Psyche, and compute integration.
 */

export {
  createDWSClient,
  type DWSClientConfig,
  type DWSJobStatus,
  DWSTrainingClient,
  getDefaultDWSConfig,
  isDWSAvailable,
  type JudgeResult,
  type RolloutAction,
  type RolloutData,
  type RolloutMetadata,
  type RolloutObservation,
  type RolloutStep,
  type TrainingJobRequest,
  type TrainingJobResult,
  type TrainingJobStatus,
} from './compute'
export {
  type APIServerConfig,
  type Board,
  type Cell,
  type Completion,
  type CompletionResult,
  createFundamentalPredictionEnv,
  createTicTacToeEnv,
  type FundamentalEnvConfig,
  FundamentalPredictionEnv,
  type GameState,
  type GameStep,
  type GameTrajectory,
  type Move,
  type Player,
  type ScoredDataGroup,
  TicTacToeEnv,
  type TrainingItem,
  trajectoryToTrainingFormat,
} from './environments'
export {
  type AtroposState,
  type BatchData,
  createAtroposServer,
  createDistributedGRPOTrainer,
  createGRPOTrainer,
  DistributedGRPOTrainer,
  type EnvConfig as AtroposEnvConfig,
  GRPOTrainer,
  type Message as AtroposMessage,
  type RegisterEnv,
  type Registration,
  type ScoredData,
  startAtroposServer,
  type TrainerStatus,
  type TrainingConfig,
  type TrainingMetrics,
} from './grpo'
export {
  type AgentTrajectory,
  AutocratTrainingClient,
  CrucibleTrainingClient,
  type CrucibleTrainingMetrics,
  type CrucibleTrajectoryStep,
  createAutocratTrainingClient,
  createCrucibleTrainingClient,
  type ModelDeploymentProposal,
  type TrainingAgentConfig,
  type TrainingEnvironment,
  type TrainingProposal,
  type TrainingRun,
  type TrajectoryMetadata,
} from './integrations'
export {
  type BridgeConfig,
  type BridgedRunState,
  type CheckpointData,
  type ClientInfo,
  type ClientRegistration,
  type CoordinatorConfig,
  type CoordinatorProgress,
  type CoordinatorState,
  CrossChainTrainingBridge,
  createCrossChainBridge,
  createPsycheClient,
  type Model,
  PsycheClient,
  type PsycheConfig,
  type PsycheTrainingMetrics,
  type RewardDistribution,
  type RunMetadata,
  type WitnessProof,
} from './psyche'

export {
  // Registry functions
  clearRubrics,
  DEFAULT_RUBRIC,
  getAllRubrics,
  getRubric,
  getRubricCount,
  getRubricOrDefault,
  hasRubric,
  type JudgeRubric,
  listRubrics,
  onRubricChange,
  type RubricRegistry,
  registerOrUpdateRubric,
  registerRubric,
  rubricRegistry,
  unregisterRubric,
  // Archetype rubrics
  ARCHETYPE_PRIORITY_METRICS,
  ARCHETYPE_RUBRICS,
  ARCHETYPE_RUBRICS_VERSION,
  ASS_KISSER_PRIORITY_METRICS,
  ASS_KISSER_RUBRIC,
  DEFAULT_ARCHETYPE_PRIORITY_METRICS,
  DEFAULT_ARCHETYPE_RUBRIC,
  DEGEN_PRIORITY_METRICS,
  DEGEN_RUBRIC,
  getAllArchetypeRubricsHash,
  getArchetypePriorityMetrics,
  getArchetypeRubric,
  getArchetypeRubricHash,
  getAvailableArchetypes,
  GOODY_TWOSHOES_PRIORITY_METRICS,
  GOODY_TWOSHOES_RUBRIC,
  hasArchetypeRubric,
  INFOSEC_PRIORITY_METRICS,
  INFOSEC_RUBRIC,
  INFORMATION_TRADER_PRIORITY_METRICS,
  INFORMATION_TRADER_RUBRIC,
  LIAR_PRIORITY_METRICS,
  LIAR_RUBRIC,
  PERPS_TRADER_PRIORITY_METRICS,
  PERPS_TRADER_RUBRIC,
  registerArchetypeRubrics,
  RESEARCHER_PRIORITY_METRICS,
  RESEARCHER_RUBRIC,
  SCAMMER_PRIORITY_METRICS,
  SCAMMER_RUBRIC,
  SOCIAL_BUTTERFLY_PRIORITY_METRICS,
  SOCIAL_BUTTERFLY_RUBRIC,
  SUPER_PREDICTOR_PRIORITY_METRICS,
  SUPER_PREDICTOR_RUBRIC,
  TRADER_PRIORITY_METRICS,
  TRADER_RUBRIC,
} from './rubrics'

export {
  AgentRegistrationResponseSchema,
  AtroposStartResponseSchema,
  BatchResponseSchema,
  CompletionResponseSchema,
  DisconnectEnvSchema,
  DWSJobStatusSchema,
  EnvRegistrationResponseSchema,
  HealthResponseSchema,
  InfoResponseSchema,
  JobAllocationsResponseSchema,
  JobIdResponseSchema,
  JobsListResponseSchema,
  JobsListResponseSchemaExternal,
  JudgeResponseSchema,
  JudgeResultSchema,
  MerkleProofResponseSchema,
  MerkleRootResponseSchema,
  MessageSchema,
  ProposalStatusResponseSchema,
  RegisterEnvSchema,
  RegisterResponseSchema,
  RegistrationSchema,
  RunInfoResponseSchema,
  ScoredDataListResponseSchema,
  ScoredDataListSchema,
  ScoredDataSchema,
  StatusResponseSchema,
  TrainingJobStatusSchema,
  // Trajectory types and schemas
  type Action,
  ActionSchema,
  type EnvironmentState,
  EnvironmentStateSchema,
  type LLMCall,
  LLMCallSchema,
  parseTrajectorySteps,
  type ProviderAccess,
  ProviderAccessSchema,
  RulerScoreResponseSchema,
  type RulerScoreResponse,
  type TrajectoryData,
  TrajectoryDataSchema,
  type TrajectoryScoreResponse,
  TrajectoryScoreResponseSchema,
  type TrajectoryStep,
  TrajectoryStepSchema,
} from './schemas'

// Metrics extraction
export {
  type BehavioralMetrics,
  type BehaviorMetrics,
  getMetricsSummary,
  type InfluenceMetrics,
  type InformationMetrics,
  type MetricsSummary,
  type SocialMetrics,
  type TradingMetrics,
  TrajectoryMetricsExtractor,
  trajectoryMetricsExtractor,
} from './metrics'

// LLM-as-judge scoring
export {
  type ArchetypeScore,
  ArchetypeScoringService,
  type CachedScore,
  type CacheStats,
  createScoringService,
  type ILLMCallerForScoring,
  type JudgeCacheConfig,
  judgePromptBuilder,
  JudgePromptBuilder,
  type JudgePromptOptions,
  LLMJudgeCache,
  llmJudgeCache,
  scoreValidator,
  type ScoringOptions,
  type TrajectoryContext,
  type ScoringTrajectoryRecord,
  type TrajectoryStepForJudge,
} from './scoring'

// HuggingFace integration
export {
  type DatasetExportConfig,
  ensureHuggingFaceRepository,
  generateModelCard,
  getHuggingFaceManualUploadInstructions,
  getHuggingFaceToken,
  type ModelUploadConfig,
  requireHuggingFaceToken,
  uploadDirectoryToHuggingFace,
  uploadFileToHuggingFace,
  uploadToHuggingFaceViaCLI,
} from './huggingface'

// App training adapters (for vendor apps like Babylon)
export {
  type AppTrainingConfig,
  AppTrainingRunner,
  type AppTrajectoryContext,
  type AppTrajectoryStep,
  type CollectOptions,
  createAppTrainingAdapter,
  getDefaultAppTrainingConfig,
  type HuggingFaceExportConfig,
  type LLMCallRecord,
  type Trajectory,
  type TrajectoryStatus,
  type TrainingDataAdapter,
  type TrainingLoopConfig,
  type TrainingLoopResult,
  type TrainingResult,
} from './apps/index.js'

// Recording infrastructure
export {
  // Window utilities
  generateWindowIds,
  getCurrentWindowId,
  getPreviousWindowId,
  getWindowIdForTimestamp,
  getWindowRange,
  isTimestampInWindow,
  isWindowComplete,
  parseWindowId,
  type ParsedWindowId,
  type WindowRange,
  // Trajectory recorder types
  type ActiveTrajectory,
  type EndTrajectoryOptions,
  type LLMCallLogRecord,
  type StartTrajectoryOptions,
  type TrajectoryRecord as StoredTrajectoryRecord,
  type TrajectoryStorage,
  // Classes
  InMemoryTrajectoryStorage,
  TrajectoryRecorder,
  // Instances
  defaultStorage,
  trajectoryRecorder,
} from './recording'

// Benchmark infrastructure
export {
  // Types
  type AgentAction,
  type A2AMethodParams,
  type A2AResponse,
  type BenchmarkComparisonResult,
  type BenchmarkConfig,
  type BenchmarkGameSnapshot,
  type BenchmarkGameState,
  type BenchmarkRunConfig,
  type BuySharesParams,
  type BuySharesResult,
  type CausalEventType,
  type ChatEntry,
  type ClosePositionResult,
  type CreateCommentResult,
  type CreatePostResult,
  type DashboardResult,
  type GroundTruth,
  type GroupChat,
  type HiddenNarrativeFact,
  type JoinGroupResult,
  type ModelConfig,
  type ModelProvider,
  type ModelTier,
  type OpenPositionResult,
  type PerpetualMarket,
  type PerpMetrics,
  type PortfolioPosition,
  type PortfolioResult,
  type Post,
  type PredictionMarket,
  type PredictionMetrics,
  type ScheduledCausalEvent,
  type SellSharesResult,
  type SimulatedAgent,
  type SimulationAgentState,
  type SimulationConfig,
  type SimulationEngineState,
  type SimulationFeedPost,
  type SimulationGroupChat,
  type SimulationMetrics,
  type SimulationPerpetualMarket,
  type SimulationPredictionMarket,
  type SimulationResult,
  type SimulationSocialMetrics,
  type Tick,
  type TickEvent,
  type TimingMetrics,
  type TrendingTagEntry,
  type VolatilityBucket,
  // Classes
  BenchmarkDataGenerator,
  SeededRandom,
  SimulationEngine,
  SimulationA2AInterface,
  // Model registry
  getAllModels,
  getBaselineModels,
  getModelById,
  getModelByModelId,
  getModelDisplayName,
  getModelsByProvider,
  getModelsByTier,
  MODEL_REGISTRY,
  registerModel,
  validateModelId,
} from './benchmark'

// Storage infrastructure
export {
  type AccessCondition,
  type AccessControlPolicy,
  type AuthSignature,
  type CIDResponse,
  type EncryptedPayload,
  type EncryptedTrajectory,
  EncryptedTrajectoryStorage,
  type EncryptionProvider,
  getEncryptedTrajectoryStorage,
  getStorage,
  getStorageProvider,
  type IPFSUploadResult,
  isCIDResponse,
  isEncryptedPayload,
  isIPFSUploadResult,
  isJsonRecord,
  type ModelMetadata,
  type PolicyCondition,
  resetEncryptedTrajectoryStorage,
  type SecretPolicy,
  shouldUseStorage,
  type StorageConfig,
  type StorageOptions,
  StorageUtil,
  type TrajectoryBatch,
} from './storage'

// TEE training workers
export {
  type BenchmarkResult as TEEBenchmarkResult,
  createTrainingWorker,
  type DataPrepResult,
  isArrayOf,
  isCIDResponse as isTEECIDResponse,
  isGenericObject,
  isJudgingScoreResponse,
  isScoredTrainingData,
  isSimulationResultResponse,
  isTEEInitResponse,
  isTEEProvider,
  isTrainingComputeResponse,
  type JudgingResult,
  type JudgingScoreResponse,
  type SimulationResultResponse,
  type TEEInitResponse,
  type TEEProvider,
  type TrainingComputeResponse,
  type TrainingResult as TEETrainingResult,
  TrainingWorker,
  type WorkerAttestation,
  type WorkerConfig,
  WorkerStatus,
  WorkerType,
} from './tee'
