#!/usr/bin/env bun
/**
 * Start Stage 2 Decentralized Stack
 * 
 * This script starts the complete Stage 2 infrastructure:
 * - L1 nodes (Geth, Reth, Nethermind)
 * - L2 sequencer nodes (Geth, Reth, Nethermind)
 * - OP Stack services (op-node, op-batcher, op-proposer)
 * - Stage 2 services (consensus, challenger, threshold signer)
 * - Proxy network (coordinator + nodes)
 * 
 * Usage:
 *   bun run scripts/start-stage2.ts
 *   bun run scripts/start-stage2.ts --deploy-contracts
 *   bun run scripts/start-stage2.ts --stop
 */

import { $ } from 'bun';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');
const SECRETS_DIR = join(ROOT, 'secrets');
const DEPLOYMENTS_DIR = join(ROOT, 'packages/contracts/deployments');
const COMPOSE_FILE = join(ROOT, 'docker-compose.stage2.yml');

// Default private keys for local development (DO NOT USE IN PRODUCTION)
const DEV_KEYS = {
  deployer: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
  sequencer1: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d',
  sequencer2: '0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a',
  sequencer3: '0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6',
  batcher: '0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a',
  proposer: '0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba',
  challenger: '0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e',
  coordinator: '0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356',
};

async function ensureSecrets(): Promise<void> {
  if (!existsSync(SECRETS_DIR)) {
    mkdirSync(SECRETS_DIR, { recursive: true });
  }

  const jwtPath = join(SECRETS_DIR, 'jwt-secret.txt');
  if (!existsSync(jwtPath)) {
    const jwt = `0x${Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('hex')}`;
    writeFileSync(jwtPath, jwt);
    console.log('✓ Generated JWT secret');
  }
}

async function createEnvFile(): Promise<void> {
  const envPath = join(ROOT, '.env.stage2');
  
  const env = `
# Stage 2 Development Environment
# Generated by start-stage2.ts

# Deployer
DEPLOYER_PRIVATE_KEY=${DEV_KEYS.deployer}

# Sequencer Keys
SEQUENCER_1_PRIVATE_KEY=${DEV_KEYS.sequencer1}
SEQUENCER_2_PRIVATE_KEY=${DEV_KEYS.sequencer2}
SEQUENCER_3_PRIVATE_KEY=${DEV_KEYS.sequencer3}

# OP Stack
BATCHER_PRIVATE_KEY=${DEV_KEYS.batcher}
PROPOSER_PRIVATE_KEY=${DEV_KEYS.proposer}
CHALLENGER_PRIVATE_KEY=${DEV_KEYS.challenger}

# Stage 2 Services
SIGNER_THRESHOLD=2

# Proxy Network
COORDINATOR_PRIVATE_KEY=${DEV_KEYS.coordinator}
NODE_1_PRIVATE_KEY=${DEV_KEYS.sequencer2}

# Contract addresses (populated after deployment)
SEQUENCER_REGISTRY_ADDRESS=
THRESHOLD_BATCH_SUBMITTER_ADDRESS=
DISPUTE_GAME_FACTORY_ADDRESS=
PROVER_ADDRESS=
PROXY_REGISTRY_ADDRESS=
PROXY_PAYMENT_ADDRESS=
`.trim();

  writeFileSync(envPath, env);
  console.log('✓ Created .env.stage2');
}

async function deployContracts(): Promise<Record<string, string>> {
  console.log('\n📜 Deploying Stage 2 contracts...\n');

  process.chdir(join(ROOT, 'packages/contracts'));
  
  // Deploy using Forge
  const result = await $`forge script script/DeployStage2.s.sol:DeployStage2 \
    --rpc-url http://localhost:8545 \
    --broadcast \
    --legacy \
    --private-key ${DEV_KEYS.deployer} 2>&1`.text();
  
  console.log(result);

  // Parse addresses from output
  const addresses: Record<string, string> = {};
  const addressMatches = result.matchAll(/(\w+Registry|\w+Timelock|\w+Factory|\w+Prover|\w+Adapter).*?(0x[a-fA-F0-9]{40})/g);
  
  for (const match of addressMatches) {
    const name = match[1].toLowerCase().replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
    addresses[name] = match[2];
  }

  // Save deployment file
  if (!existsSync(DEPLOYMENTS_DIR)) {
    mkdirSync(DEPLOYMENTS_DIR, { recursive: true });
  }

  const deploymentPath = join(DEPLOYMENTS_DIR, 'stage2-localnet.json');
  writeFileSync(deploymentPath, JSON.stringify({
    network: 'localnet',
    chainId: 1337,
    deployer: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
    timestamp: Date.now(),
    sequencerRegistry: addresses.sequencer_registry || '',
    governanceTimelock: addresses.governance_timelock || '',
    disputeGameFactory: addresses.dispute_game_factory || '',
    prover: addresses.prover || '',
    l2OutputOracleAdapter: addresses.l2_output_oracle_adapter || '',
    optimismPortalAdapter: addresses.optimism_portal_adapter || '',
  }, null, 2));

  console.log(`\n✓ Deployment saved to ${deploymentPath}`);
  return addresses;
}

async function startServices(): Promise<void> {
  console.log('\n🚀 Starting Stage 2 services...\n');

  // Start docker-compose
  process.chdir(ROOT);
  
  await $`docker-compose -f ${COMPOSE_FILE} --env-file .env.stage2 up -d geth-l1 2>&1`.text();
  console.log('✓ Started L1 Geth');

  // Wait for L1 to be ready
  console.log('⏳ Waiting for L1...');
  await Bun.sleep(5000);
  
  // Check L1 health
  let l1Ready = false;
  for (let i = 0; i < 30; i++) {
    try {
      const resp = await fetch('http://localhost:8545', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ jsonrpc: '2.0', method: 'eth_blockNumber', params: [], id: 1 }),
      });
      if (resp.ok) {
        l1Ready = true;
        break;
      }
    } catch {
      await Bun.sleep(1000);
    }
  }

  if (!l1Ready) {
    console.error('✗ L1 not ready after 30s');
    process.exit(1);
  }
  console.log('✓ L1 is ready');

  // Deploy contracts if requested
  if (process.argv.includes('--deploy-contracts')) {
    await deployContracts();
  }

  // Start remaining services
  await $`docker-compose -f ${COMPOSE_FILE} --env-file .env.stage2 up -d 2>&1`.text();
  console.log('✓ Started all services');
}

async function stopServices(): Promise<void> {
  console.log('\n🛑 Stopping Stage 2 services...\n');
  
  process.chdir(ROOT);
  await $`docker-compose -f ${COMPOSE_FILE} down 2>&1`.text();
  console.log('✓ Stopped all services');
}

async function showStatus(): Promise<void> {
  console.log('\n📊 Stage 2 Status\n');

  process.chdir(ROOT);
  const status = await $`docker-compose -f ${COMPOSE_FILE} ps --format json 2>&1`.text();
  
  try {
    const services = status.split('\n').filter(Boolean).map(line => {
      try {
        return JSON.parse(line);
      } catch {
        return null;
      }
    }).filter(Boolean);

    console.log('Service'.padEnd(30) + 'Status'.padEnd(15) + 'Ports');
    console.log('-'.repeat(70));

    for (const svc of services) {
      const name = (svc.Name || svc.Service || 'unknown').padEnd(30);
      const state = (svc.State || svc.Status || 'unknown').padEnd(15);
      const ports = svc.Ports || svc.Publishers?.map((p: { PublishedPort: number }) => p.PublishedPort).join(', ') || '';
      console.log(`${name}${state}${ports}`);
    }
  } catch {
    console.log(status);
  }

  // Check endpoints
  console.log('\n🔌 Endpoints:\n');
  
  const endpoints = [
    { name: 'L1 Geth', url: 'http://localhost:8545' },
    { name: 'L1 Reth', url: 'http://localhost:8645' },
    { name: 'L1 Nethermind', url: 'http://localhost:8745' },
    { name: 'L2 Geth Seq', url: 'http://localhost:9545' },
    { name: 'L2 Reth Seq', url: 'http://localhost:9645' },
    { name: 'L2 Nethermind Seq', url: 'http://localhost:9745' },
    { name: 'Proxy Coordinator', url: 'http://localhost:4020/health' },
    { name: 'Prometheus', url: 'http://localhost:9090' },
    { name: 'Grafana', url: 'http://localhost:3001' },
  ];

  for (const ep of endpoints) {
    try {
      const resp = await fetch(ep.url, { signal: AbortSignal.timeout(2000) });
      console.log(`  ${ep.name.padEnd(20)} ${resp.ok ? '✓' : '✗'} ${ep.url}`);
    } catch {
      console.log(`  ${ep.name.padEnd(20)} ✗ ${ep.url}`);
    }
  }
}

async function main(): Promise<void> {
  console.log(`
╔══════════════════════════════════════════════════════════════════╗
║                 Network Stage 2 Decentralization                    ║
╚══════════════════════════════════════════════════════════════════╝
`);

  if (process.argv.includes('--stop')) {
    await stopServices();
    return;
  }

  if (process.argv.includes('--status')) {
    await showStatus();
    return;
  }

  // Ensure prerequisites
  await ensureSecrets();
  await createEnvFile();
  
  // Start services
  await startServices();
  
  // Show status
  await Bun.sleep(5000);
  await showStatus();

  console.log(`
╔══════════════════════════════════════════════════════════════════╗
║  Stage 2 is running. Use --status to check, --stop to shutdown. ║
╚══════════════════════════════════════════════════════════════════╝
`);
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});

